### PR TITLE
Make noarch

### PR DESCRIPTION
**Pull request by xylar**
Also changed to `pip` install

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@asmeurer, it looks like you're not particularly inclined to maintain this feedstock.  If that's correct, would you be willing to merge this PR to add me as a maintainer and I'll take over?

**Comment by scopatz** [comment]
I am pretty sure Aaron won't mind

**Comment by asmeurer** [comment]
Yeah I'm always happy to have more maintainers on feedstocks.

**Pull request merged**
